services:
  DBP\API\AuthenticDocumentBundle\Service\AuthenticDocumentApi:
    public: false
    autowire: true

  DBP\API\AuthenticDocumentBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true

  DBP\API\AuthenticDocumentBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  DBP\API\AuthenticDocumentBundle\MessageHandler\AuthenticDocumentRequestHandler:
    public: false
    autowire: true
    autoconfigure: true
    tags: ['messenger.message_handler']

  DBP\API\AuthenticDocumentBundle\Command\MessageTestCommand:
    public: false
    autowire: true
    autoconfigure: true

  DBP\API\AuthenticDocumentBundle\Command\MailTestCommand:
    public: false
    autowire: true
    autoconfigure: true

  DBP\API\AuthenticDocumentBundle\Service\CampusOnlineApi:
    autowire: true
    autoconfigure: true

  DBP\API\AuthenticDocumentBundle\Service\AuthenticDocumentHandlerProviderInterface:
    '@DBP\API\AuthenticDocumentBundle\Service\CampusOnlineApi'

  # This alias exist so we can replace the service during tests
  test.App\Service\AuthenticDocumentHandlerProviderInterface:
    alias: 'DBP\API\AuthenticDocumentBundle\Service\AuthenticDocumentHandlerProviderInterface'
    public: true
