services:
  DBP\API\AuthenticDocumentBundle\Service\AuthenticDocumentApi:
    public: false
    autowire: true

  DBP\API\AuthenticDocumentBundle\DataPersister\:
    resource: '../../DataPersister'
    tags: ['api_platform.data_persister']
    autowire: true

  DBP\API\AuthenticDocumentBundle\DataProvider\AuthenticDocumentTypeItemDataProvider:
    tags: [{ name: 'api_platform.item_data_provider'}]
    autowire: true

  DBP\API\AuthenticDocumentBundle\DataProvider\AuthenticDocumentTypeCollectionDataProvider:
    tags: [{ name: 'api_platform.collection_data_provider'}]
    autowire: true

  DBP\API\AuthenticDocumentBundle\MessageHandler\AuthenticDocumentRequestHandler:
    public: false
    autowire: true
    autoconfigure: true
    tags: ['messenger.message_handler']

  DBP\API\AuthenticDocumentBundle\Command\MessageTestCommand:
    public: false
    autowire: true
    autoconfigure: true
