services:
  DBP\API\AuthenticDocumentBundle\Service\AuthenticDocumentApi:
    autowire: true
    autoconfigure: true

  DBP\API\AuthenticDocumentBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true

  DBP\API\AuthenticDocumentBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  DBP\API\AuthenticDocumentBundle\MessageHandler\AuthenticDocumentRequestHandler:
    public: false
    autowire: true
    autoconfigure: true
    tags: ['messenger.message_handler']

  DBP\API\AuthenticDocumentBundle\Command\MessageTestCommand:
    public: false
    autowire: true
    autoconfigure: true

  DBP\API\AuthenticDocumentBundle\Command\MailTestCommand:
    public: false
    autowire: true
    autoconfigure: true

  DBP\API\AuthenticDocumentBundle\Command\PictureFetchCommand:
    public: false
    autowire: true
    autoconfigure: true

  DBP\API\AuthenticDocumentBundle\Command\PictureUploadCommand:
    public: false
    autowire: true
    autoconfigure: true

  DBP\API\AuthenticDocumentBundle\UCard\UCardAPI:
    autowire: true
    autoconfigure: true

  DBP\API\AuthenticDocumentBundle\Service\CampusOnlineStorage:
    autowire: true
    autoconfigure: true

  DBP\API\AuthenticDocumentBundle\DocumentHandler\DocumentHandler:
    autowire: true
    autoconfigure: true

  DBP\API\AuthenticDocumentBundle\API\DocumentStorageInterface:
    '@DBP\API\AuthenticDocumentBundle\Service\CampusOnlineStorage'